version: "3.1"
services:
  springkafkaapp:
    image: springkafkaapp
    environment:
      - KAFKA_IP_PORT=kafka:9092
    ports:
      - "8080:8080"
    build:
      context: "./"
      dockerfile: Dockerfile

